"""initial migration

Revision ID: 61d5a1f175ae
Revises: 1a77ca03d3c8
Create Date: 2026-03-02 13:54:30.149195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61d5a1f175ae'
down_revision: Union[str, Sequence[str], None] = '1a77ca03d3c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'destination')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('destination', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
